[tool.poetry]
name = "microfunkhaus"
version = "0.1.0"
description = "A facade/gateway microservice to rule them all."
authors = ["Arthur Ryzhak <ryzhakar@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.79"
aiohttp = "^3.8.1"
uvicorn = "^0.18.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
